// Generated by CoffeeScript 1.5.0-pre
(function() {
  var Bug, Entity, Route, TdApp, Tower, kata,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Route = (function() {

    Route.prototype.points = [];

    Route.prototype.draw = function() {
      var i, _i, _ref;
      this.context.strokeStyle = "#888";
      this.context.beginPath();
      for (i = _i = 0, _ref = this.points.length - 1; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.context.moveTo(this.points[i][0], this.points[i][1]);
        this.context.lineTo(this.points[i + 1][0], this.points[i + 1][1]);
      }
      return this.context.stroke();
    };

    function Route(context, points) {
      this.context = context;
      this.points = points;
    }

    Route.prototype.crossproduct = function(ax, ay, bx, by_, cx, cy) {
      return (cy - ay) * (bx - ax) - (cx - ax) * (by_ - ay);
    };

    Route.prototype.dotproduct = function(ax, ay, bx, by_, cx, cy) {
      return (cx - ax) * (bx - ax) + (cy - ay) * (by_ - ay);
    };

    Route.prototype.between = function(ax, ay, bx, by_, cx, cy) {
      if (Math.abs(this.crossproduct(ax, ay, bx, by_, cx, cy)) > 0) {
        return false;
      }
      if ((this.dotproduct(ax, ay, bx, by_, cx, cy)) < 0) {
        return false;
      }
      if ((this.dotproduct(ax, ay, bx, by_, cx, cy)) >= ((ax - bx) * (ax - bx) + (ay - by_) * (ay - by_))) {
        return false;
      }
      return true;
    };

    Route.prototype.getv = function(x, y) {
      var ax, ay, bx, by_, i, vx, vy, _i, _ref, _ref1, _ref2;
      for (i = _i = 0, _ref = this.points.length - 1; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        _ref1 = this.points[i], ax = _ref1[0], ay = _ref1[1];
        _ref2 = this.points[i + 1], bx = _ref2[0], by_ = _ref2[1];
        if (this.between(ax, ay, bx, by_, x, y)) {
          vx = ax !== bx ? (ax > bx ? -1 : 1) : 0;
          vy = ay !== by_ ? (ay > by_ ? -1 : 1) : 0;
          return [vx, vy];
        }
      }
      return [0, 0];
    };

    return Route;

  })();

  Entity = (function() {

    Entity.prototype.x = 0;

    Entity.prototype.y = 0;

    Entity.prototype.vx = 0;

    Entity.prototype.vy = 0;

    Entity.prototype.state = "green";

    function Entity(context, x, y, route, name) {
      this.context = context;
      this.x = x;
      this.y = y;
      this.route = route;
      this.name = name != null ? name : "unnamed";
    }

    return Entity;

  })();

  Bug = (function(_super) {

    __extends(Bug, _super);

    function Bug() {
      return Bug.__super__.constructor.apply(this, arguments);
    }

    Bug.prototype.hp = 20;

    Bug.prototype.update = function() {
      var _ref;
      _ref = this.route.getv(this.x, this.y), this.vx = _ref[0], this.vy = _ref[1];
      this.x += this.vx;
      return this.y += this.vy;
    };

    Bug.prototype.draw = function() {
      this.context.fillStyle = this.state === "green" ? 'rgba(0,180,0,0.8)' : 'rgba(0,0,180,0.8)';
      this.context.fillStyle = '#0F0';
      this.context.beginPath();
      this.context.arc(this.x, this.y, this.hp, 0, Math.PI * 2, true);
      this.context.closePath();
      return this.context.fill();
    };

    return Bug;

  })(Entity);

  Tower = (function() {

    Tower.prototype.x = 0;

    Tower.prototype.y = 0;

    function Tower(context, x, y) {
      this.context = context;
      this.x = x;
      this.y = y;
    }

    Tower.prototype.draw = function() {
      this.context.fillStyle = 'rgba(0,0,0,1)';
      return this.context.fillRect(this.x, this.y, 15, 15);
    };

    Tower.prototype.update = function(entities) {
      var e, _i, _len, _ref;
      this.entities = entities;
      _ref = this.entities;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        e = _ref[_i];
        if (Math.sqrt((e.x - this.x) * (e.x - this.x) + (e.y - this.y) * (e.y - this.y)) < 100) {
          this.context.beginPath();
          this.context.strokeStyle = "#F00";
          this.context.moveTo(this.x, this.y);
          this.context.lineTo(e.x, e.y);
          this.context.stroke();
          e.hp -= 0.2;
          return true;
        }
      }
    };

    return Tower;

  })();

  TdApp = (function() {

    function TdApp() {}

    TdApp.prototype.timeout = 50;

    TdApp.prototype.main = function() {
      this.createCanvas();
      this.startNewGame();
      return this.addKeyObservers();
    };

    TdApp.prototype.startNewGame = function() {
      this.entities = [];
      this.route = new Route(this.context, [[100, 100], [100, 200], [200, 200], [200, 100], [300, 100], [300, 300], [400, 300], [400, 100], [520, 100]]);
      this.towers = [];
      this.entities.push(new Bug(this.context, 100, 100, this.route, "A"));
      return this.runLoop();
    };

    TdApp.prototype.runLoop = function() {
      var _this = this;
      return setTimeout(function() {
        var alive, e, _i, _j, _len, _len1, _ref, _ref1;
        _this.entities.forEach(function(e) {
          return e.update();
        });
        console.log((function() {
          var _i, _len, _ref, _results;
          _ref = this.entities;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            e = _ref[_i];
            _results.push(e.name + e.hp);
          }
          return _results;
        }).call(_this));
        alive = [];
        _ref = _this.entities;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          e = _ref[_i];
          if (e.hp > 0) {
            alive.push(e);
          }
        }
        _this.entities = alive;
        _this.clearCanvas();
        _this.drawField();
        _this.route.draw();
        _this.drawEntities();
        _this.towers.forEach(function(e) {
          return e.draw();
        });
        _ref1 = _this.towers;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          e = _ref1[_j];
          e.update(_this.entities);
        }
        if (!_this.terminateRunLoop) {
          return _this.runLoop();
        }
      }, this.timeout);
    };

    TdApp.prototype.drawField = function() {
      this.context.fillStyle = 'rgba(200,150,150,0.2)';
      return this.context.fillRect(50, 50, 600, 300);
    };

    TdApp.prototype.drawEntities = function() {
      var e, _i, _len, _ref, _results;
      _ref = this.entities;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        e = _ref[_i];
        _results.push(e.draw());
      }
      return _results;
    };

    TdApp.prototype.createCanvas = function() {
      this.canvas = $('#canvas')[0];
      this.context = this.canvas.getContext('2d');
      this.canvas.width = document.width;
      return this.canvas.height = document.height;
    };

    TdApp.prototype.clearCanvas = function() {
      return this.context.clearRect(0, 0, this.canvas.width, this.canvas.height);
    };

    TdApp.prototype.addKeyObservers = function() {
      var _this = this;
      $(".stop").click(function() {
        return _this.terminateRunLoop = true;
      });
      $(".start").click(function() {
        return _this.terminateRunLoop = true;
      });
      $(".left").click(function() {
        _this.entities[0].vx = -1;
        return _this.entities[0].vy = 0;
      });
      $(".right").click(function() {
        _this.entities[0].vx = 1;
        return _this.entities[0].vy = 0;
      });
      $(".up").click(function() {
        _this.entities[0].vy = -1;
        return _this.entities[0].vx = 0;
      });
      $(".down").click(function() {
        _this.entities[0].vy = 1;
        return _this.entities[0].vx = 0;
      });
      $(".plus").click(function() {
        return _this.timeout = _this.timeout / 2;
      });
      $(".minus").click(function() {
        return _this.timeout = _this.timeout * 2;
      });
      $(".spawn").click(function() {
        console.log("spawn");
        return _this.entities.push(new Bug(_this.context, 100, 100, _this.route, Math.round(Math.random() * 15).toString()));
      });
      return $("#canvas").bind('click', function(event) {
        console.log(event);
        return _this.towers.push(new Tower(_this.context, event.layerX, event.layerY));
      });
    };

    return TdApp;

  })();

  window.onload = function() {
    window.td = new TdApp;
    return window.td.main();
  };

  kata = function() {
    return console.log("blah blah blah");
  };

}).call(this);
